### ISSUE TITLE
Click Http Request Smuggler Unable to load to Turb Inturder. Burpsuite 2022.2.2

### ISSUE THREAD

**Issue by ltfafei** [PortSwigger/http-request-smuggler#51]
Hello,

Click Http Request Smuggler Unable to load to Turb Inturder. Burpsuite 2022.2.2

**Comment by tobmay** [comment]
**Same issue here: Turbo Intruder window never opens (for probing)**

This happens for "HTTP Request Smuggler -> Smuggle Probe" and all other probes in this menu. 
However, it does open Turbo Intruder for manipulated request (e.g. POST, chunked transport encoding) such that "HTTP Request Smuggler -> Smuggle Attack (CE.TL)" (and "Smuggle Attack (CE.TL)") appear in menu.

Both extensions installed via BApp Store after a fresh installation of BurpSuite.
- BurpSuite Professional v2022.8.5
- Turbo Intruder v1.30
- Request Smuggler v2.13

**Comment by albinowax** [comment]
Probes and scans are not expected to launch a turbo intruder window, as they're fully automatic. Connection errors are also expected, due to the payloads sent by the scans. If a scan detects any vulnerabilities, they will be reported as scanner issues (if you're using pro) or printed in the extension output (if you're on community)

**Comment by tobmay** [comment]
Awesome, thanks a lot for the clarifications
